services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules

  auth-service:
    build: ./services/auth-service
    ports:
      - 4000:4000
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    environment:
      - PORT=4000

  user-service:
    build: ./services/user-service
    ports:
      - 4001:4001
    volumes:
      - ./services/user-service:/app
      - /app/node_modules
    environment:
      - PORT=4001

  # user-db:
  #   image: mongo:latest
  #   container_name: user-db
  #   volumes:  # TODO: Add db-init.js script
  #     - user-db-data:/data/db
  #   ports:
  #     - 27017:27017

  gateway:
    build: ./gateway
    ports:
      - 80:80
