services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - GATEWAY_URL=http://gateway

  auth-service:
    build: ./services/auth-service
    ports:
      - 4000:4000
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    environment:
      - PORT=4000
      - DB_URI=mongodb://auth-service-db:27017/auth-service-db

  auth-service-db:
    image: mongo:latest
    container_name: auth-service-db
    volumes:
      - auth-service-db-vol:/data/db

  confluence-service:
    build: ./services/confluence-service
    ports:
      - 4010:4010
    volumes:
      - ./services/confluence-service:/app
      - /app/node_modules
    environment:
      - PORT=4010

  distributary-service:
    build: ./services/distributary-service
    ports:
      - 4011:4011
    volumes:
      - ./services/distributary-service:/app
      - /app/node_modules
    environment:
      - PORT=4011

  redis-broker-service:
    image: redis/redis-stack:latest
    container_name: redis-broker-service
    ports:
      - 4020:6379
      - 8001:8001  # for Redis Insight
    volumes:
      - redis-broker-service-vol:/data  # TODO: Check if this is correct


  # user-service:
  #   build: ./services/user-service
  #   ports:
  #     - 4001:4001
  #   volumes:
  #     - ./services/user-service:/app
  #     - /app/node_modules
  #   environment:
  #     - PORT=4001

  gateway:
    build: ./gateway
    ports:
      - 80:80

volumes:
  auth-service-db-vol:
  redis-broker-service-vol: