services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000 # Expose frontend locally

  user-service:
    build: ./services/user-service
    ports:
      - 4000:4000 # Expose user-service locally

  gateway:
    build: ./gateway
    ports:
      - 80:80 # Expose API Gateway locally
