services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - GATEWAY_URL=http://gateway

  auth-service:
    build: ./services/auth-service
    ports:
      - 4000:4000
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    environment:
      - PORT=4000
      - DB_URI=mongodb://auth-service-db:27017/auth-service-db

  auth-service-db:
    image: mongo:latest
    container_name: auth-service-db
    volumes:
      - auth-service-db-vol:/data/db

  # user-service:
  #   build: ./services/user-service
  #   ports:
  #     - 4001:4001
  #   volumes:
  #     - ./services/user-service:/app
  #     - /app/node_modules
  #   environment:
  #     - PORT=4001

  gateway:
    build: ./gateway
    ports:
      - 80:80

volumes:
  auth-service-db-vol: